-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

vim.keymap.set("n", "<leader>da", function()
  require("dap").continue()
end, { desc = "Continue" })
vim.keymap.set("n", "<leader>de", function()
  require("dap").run_to_cursor()
end, { desc = "Run to cursor" })
-- TODO: `dd` should start last debugging session (with recompilation) if no active session.
vim.keymap.set("n", "<leader>dd", function()
  require("dap").step_over()
end, { desc = "Step over" })
vim.keymap.set("n", "<leader>df", function()
  require("dap").step_into()
end, { desc = "Step into" })
vim.keymap.set("n", "<leader>dg", function()
  require("dap").step_out()
end, { desc = "Step out" })
vim.keymap.set("n", "<leader>dr", function()
  require("dap").restart()
end, { desc = "Restart" })
vim.keymap.set("n", "<leader>ds", function()
  require("dap").pause()
end, { desc = "Pause" })
vim.keymap.set("n", "<leader>du", function()
  require("dapui").toggle()
end, { desc = "Toggle debug ui" })
vim.keymap.set("n", "<leader>dv", function()
  require("dap").toggle_breakpoint()
end, { desc = "Toggle breakpoint" })
vim.keymap.set("n", "<leader>dt", function()
  require("dap").terminate()
end, { desc = "Terminate" })
